window.esdocSearchIndex = [
  [
    "teste/src/model/bar.js~bar",
    "class/src/model/Bar.js~Bar.html",
    "<span>Bar</span> <span class=\"search-result-import-path\">teste/src/model/Bar.js</span>",
    "class"
  ],
  [
    "teste/src/model/bar/beat.js~beat",
    "class/src/model/bar/Beat.js~Beat.html",
    "<span>Beat</span> <span class=\"search-result-import-path\">teste/src/model/bar/Beat.js</span>",
    "class"
  ],
  [
    "teste/src/util/comparable.js~comparable",
    "class/src/util/Comparable.js~Comparable.html",
    "<span>Comparable</span> <span class=\"search-result-import-path\">teste/src/util/Comparable.js</span>",
    "class"
  ],
  [
    "teste/src/util/drawlog.js~drawlog",
    "class/src/util/DrawLog.js~DrawLog.html",
    "<span>DrawLog</span> <span class=\"search-result-import-path\">teste/src/util/DrawLog.js</span>",
    "class"
  ],
  [
    "teste/src/model/drawable.js~drawable",
    "class/src/model/Drawable.js~Drawable.html",
    "<span>Drawable</span> <span class=\"search-result-import-path\">teste/src/model/Drawable.js</span>",
    "class"
  ],
  [
    "teste/src/model/bar/note/flag.js~flag",
    "class/src/model/bar/note/Flag.js~Flag.html",
    "<span>Flag</span> <span class=\"search-result-import-path\">teste/src/model/bar/note/Flag.js</span>",
    "class"
  ],
  [
    "teste/src/glyph/font.js~font",
    "class/src/glyph/Font.js~Font.html",
    "<span>Font</span> <span class=\"search-result-import-path\">teste/src/glyph/Font.js</span>",
    "class"
  ],
  [
    "teste/src/glyph/glyph.js~glyph",
    "class/src/glyph/Glyph.js~Glyph.html",
    "<span>Glyph</span> <span class=\"search-result-import-path\">teste/src/glyph/Glyph.js</span>",
    "class"
  ],
  [
    "teste/src/glyph/glyphcode.js~glyphcode",
    "class/src/glyph/GlyphCode.js~GlyphCode.html",
    "<span>GlyphCode</span> <span class=\"search-result-import-path\">teste/src/glyph/GlyphCode.js</span>",
    "class"
  ],
  [
    "teste/src/model/bar/note/head.js~head",
    "class/src/model/bar/note/Head.js~Head.html",
    "<span>Head</span> <span class=\"search-result-import-path\">teste/src/model/bar/note/Head.js</span>",
    "class"
  ],
  [
    "teste/src/constants/keyname.js~key_name",
    "variable/index.html#static-variable-KEY_NAME",
    "<span>KEY_NAME</span> <span class=\"search-result-import-path\">teste/src/constants/KeyName.js</span>",
    "variable"
  ],
  [
    "teste/src/model/bar/note/key.js~key",
    "class/src/model/bar/note/Key.js~Key.html",
    "<span>Key</span> <span class=\"search-result-import-path\">teste/src/model/bar/note/Key.js</span>",
    "class"
  ],
  [
    "teste/src/constants/keyname.js~keynamelist",
    "variable/index.html#static-variable-KeyNameList",
    "<span>KeyNameList</span> <span class=\"search-result-import-path\">teste/src/constants/KeyName.js</span>",
    "variable"
  ],
  [
    "teste/src/model/bar/note.js~note",
    "class/src/model/bar/Note.js~Note.html",
    "<span>Note</span> <span class=\"search-result-import-path\">teste/src/model/bar/Note.js</span>",
    "class"
  ],
  [
    "teste/src/constants/note.js~noteduration",
    "variable/index.html#static-variable-NoteDuration",
    "<span>NoteDuration</span> <span class=\"search-result-import-path\">teste/src/constants/Note.js</span>",
    "variable"
  ],
  [
    "teste/src/constants/note.js~notemodifier",
    "variable/index.html#static-variable-NoteModifier",
    "<span>NoteModifier</span> <span class=\"search-result-import-path\">teste/src/constants/Note.js</span>",
    "variable"
  ],
  [
    "teste/src/constants/note.js~noteorientation",
    "variable/index.html#static-variable-NoteOrientation",
    "<span>NoteOrientation</span> <span class=\"search-result-import-path\">teste/src/constants/Note.js</span>",
    "variable"
  ],
  [
    "teste/src/model/bar/noteutil.js~noteutil",
    "class/src/model/bar/NoteUtil.js~NoteUtil.html",
    "<span>NoteUtil</span> <span class=\"search-result-import-path\">teste/src/model/bar/NoteUtil.js</span>",
    "class"
  ],
  [
    "teste/src/util/observable.js~observable",
    "class/src/util/Observable.js~Observable.html",
    "<span>Observable</span> <span class=\"search-result-import-path\">teste/src/util/Observable.js</span>",
    "class"
  ],
  [
    "teste/src/glyph/outline.js~outline",
    "class/src/glyph/Outline.js~Outline.html",
    "<span>Outline</span> <span class=\"search-result-import-path\">teste/src/glyph/Outline.js</span>",
    "class"
  ],
  [
    "teste/src/test/data.js~score",
    "variable/index.html#static-variable-SCORE",
    "<span>SCORE</span> <span class=\"search-result-import-path\">teste/src/test/data.js</span>",
    "variable"
  ],
  [
    "teste/src/model/score.js~score",
    "class/src/model/Score.js~Score.html",
    "<span>Score</span> <span class=\"search-result-import-path\">teste/src/model/Score.js</span>",
    "class"
  ],
  [
    "teste/src/model/staff.js~staff",
    "class/src/model/Staff.js~Staff.html",
    "<span>Staff</span> <span class=\"search-result-import-path\">teste/src/model/Staff.js</span>",
    "class"
  ],
  [
    "teste/src/model/clef/trebleclef.js~trebleclef",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html",
    "<span>TrebleClef</span> <span class=\"search-result-import-path\">teste/src/model/clef/TrebleClef.js</span>",
    "class"
  ],
  [
    "teste/src/createscore.js~createscore",
    "function/index.html#static-function-createScore",
    "<span>createScore</span> <span class=\"search-result-import-path\">teste/src/createScore.js</span>",
    "function"
  ],
  [
    "teste/src/constants/renderercontextprops.js~getprops",
    "variable/index.html#static-variable-getProps",
    "<span>getProps</span> <span class=\"search-result-import-path\">teste/src/constants/RendererContextProps.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/canvasrenderingcontext.js",
    "file/src/CanvasRenderingContext.js.html",
    "src/CanvasRenderingContext.js",
    "file"
  ],
  [
    "src/renderercontext.js",
    "file/src/RendererContext.js.html",
    "src/RendererContext.js",
    "file"
  ],
  [
    "src/constants/keyname.js",
    "file/src/constants/KeyName.js.html",
    "src/constants/KeyName.js",
    "file"
  ],
  [
    "src/constants/note.js",
    "file/src/constants/Note.js.html",
    "src/constants/Note.js",
    "file"
  ],
  [
    "src/constants/renderercontextprops.js",
    "file/src/constants/RendererContextProps.js.html",
    "src/constants/RendererContextProps.js",
    "file"
  ],
  [
    "src/createscore.js",
    "file/src/createScore.js.html",
    "src/createScore.js",
    "file"
  ],
  [
    "src/font/gonville.js",
    "file/src/font/gonville.js.html",
    "src/font/gonville.js",
    "file"
  ],
  [
    "src/glyph/font.js",
    "file/src/glyph/Font.js.html",
    "src/glyph/Font.js",
    "file"
  ],
  [
    "src/glyph/font.js~font#constructor",
    "class/src/glyph/Font.js~Font.html#instance-constructor-constructor",
    "src/glyph/Font.js~Font#constructor",
    "method"
  ],
  [
    "src/glyph/font.js~font#familyname",
    "class/src/glyph/Font.js~Font.html#instance-member-familyName",
    "src/glyph/Font.js~Font#familyName",
    "member"
  ],
  [
    "src/glyph/font.js~font#glyphs",
    "class/src/glyph/Font.js~Font.html#instance-member-glyphs",
    "src/glyph/Font.js~Font#glyphs",
    "member"
  ],
  [
    "src/glyph/font.js~font.getdefault",
    "class/src/glyph/Font.js~Font.html#static-method-getDefault",
    "src/glyph/Font.js~Font.getDefault",
    "method"
  ],
  [
    "src/glyph/glyph.js",
    "file/src/glyph/Glyph.js.html",
    "src/glyph/Glyph.js",
    "file"
  ],
  [
    "src/glyph/glyph.js~glyph#constructor",
    "class/src/glyph/Glyph.js~Glyph.html#instance-constructor-constructor",
    "src/glyph/Glyph.js~Glyph#constructor",
    "method"
  ],
  [
    "src/glyph/glyph.js~glyph#glyph",
    "class/src/glyph/Glyph.js~Glyph.html#instance-member-glyph",
    "src/glyph/Glyph.js~Glyph#glyph",
    "member"
  ],
  [
    "src/glyph/glyph.js~glyph#height",
    "class/src/glyph/Glyph.js~Glyph.html#instance-member-height",
    "src/glyph/Glyph.js~Glyph#height",
    "member"
  ],
  [
    "src/glyph/glyph.js~glyph#outline",
    "class/src/glyph/Glyph.js~Glyph.html#instance-member-outline",
    "src/glyph/Glyph.js~Glyph#outline",
    "member"
  ],
  [
    "src/glyph/glyph.js~glyph#render",
    "class/src/glyph/Glyph.js~Glyph.html#instance-method-render",
    "src/glyph/Glyph.js~Glyph#render",
    "method"
  ],
  [
    "src/glyph/glyph.js~glyph#width",
    "class/src/glyph/Glyph.js~Glyph.html#instance-member-width",
    "src/glyph/Glyph.js~Glyph#width",
    "member"
  ],
  [
    "src/glyph/glyph.js~glyph.create",
    "class/src/glyph/Glyph.js~Glyph.html#static-method-create",
    "src/glyph/Glyph.js~Glyph.create",
    "method"
  ],
  [
    "src/glyph/glyphcode.js",
    "file/src/glyph/GlyphCode.js.html",
    "src/glyph/GlyphCode.js",
    "file"
  ],
  [
    "src/glyph/glyphcode.js~glyphcode.getfromname",
    "class/src/glyph/GlyphCode.js~GlyphCode.html#static-method-getFromName",
    "src/glyph/GlyphCode.js~GlyphCode.getFromName",
    "method"
  ],
  [
    "src/glyph/outline.js",
    "file/src/glyph/Outline.js.html",
    "src/glyph/Outline.js",
    "file"
  ],
  [
    "src/glyph/outline.js~outline.render",
    "class/src/glyph/Outline.js~Outline.html#static-method-render",
    "src/glyph/Outline.js~Outline.render",
    "method"
  ],
  [
    "src/main.js",
    "file/src/main.js.html",
    "src/main.js",
    "file"
  ],
  [
    "src/model/bar.js",
    "file/src/model/Bar.js.html",
    "src/model/Bar.js",
    "file"
  ],
  [
    "src/model/bar.js~bar#addnote",
    "class/src/model/Bar.js~Bar.html#instance-method-addNote",
    "src/model/Bar.js~Bar#addNote",
    "method"
  ],
  [
    "src/model/bar.js~bar#constructor",
    "class/src/model/Bar.js~Bar.html#instance-constructor-constructor",
    "src/model/Bar.js~Bar#constructor",
    "method"
  ],
  [
    "src/model/bar.js~bar#draw",
    "class/src/model/Bar.js~Bar.html#instance-method-draw",
    "src/model/Bar.js~Bar#draw",
    "method"
  ],
  [
    "src/model/bar.js~bar#drawtimesignature",
    "class/src/model/Bar.js~Bar.html#instance-method-drawTimeSignature",
    "src/model/Bar.js~Bar#drawTimeSignature",
    "method"
  ],
  [
    "src/model/bar.js~bar#getnotes",
    "class/src/model/Bar.js~Bar.html#instance-method-getNotes",
    "src/model/Bar.js~Bar#getNotes",
    "method"
  ],
  [
    "src/model/bar.js~bar#getwidth",
    "class/src/model/Bar.js~Bar.html#instance-method-getWidth",
    "src/model/Bar.js~Bar#getWidth",
    "method"
  ],
  [
    "src/model/bar.js~bar#isnewline",
    "class/src/model/Bar.js~Bar.html#instance-method-isNewLine",
    "src/model/Bar.js~Bar#isNewLine",
    "method"
  ],
  [
    "src/model/bar.js~bar#setnewline",
    "class/src/model/Bar.js~Bar.html#instance-method-setNewLine",
    "src/model/Bar.js~Bar#setNewLine",
    "method"
  ],
  [
    "src/model/drawable.js",
    "file/src/model/Drawable.js.html",
    "src/model/Drawable.js",
    "file"
  ],
  [
    "src/model/drawable.js~drawable#afterdraw",
    "class/src/model/Drawable.js~Drawable.html#instance-method-afterDraw",
    "src/model/Drawable.js~Drawable#afterDraw",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#beforedraw",
    "class/src/model/Drawable.js~Drawable.html#instance-method-beforeDraw",
    "src/model/Drawable.js~Drawable#beforeDraw",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#constructor",
    "class/src/model/Drawable.js~Drawable.html#instance-constructor-constructor",
    "src/model/Drawable.js~Drawable#constructor",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#draw",
    "class/src/model/Drawable.js~Drawable.html#instance-method-draw",
    "src/model/Drawable.js~Drawable#draw",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#getheight",
    "class/src/model/Drawable.js~Drawable.html#instance-method-getHeight",
    "src/model/Drawable.js~Drawable#getHeight",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#getpadding",
    "class/src/model/Drawable.js~Drawable.html#instance-method-getPadding",
    "src/model/Drawable.js~Drawable#getPadding",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#getwidth",
    "class/src/model/Drawable.js~Drawable.html#instance-method-getWidth",
    "src/model/Drawable.js~Drawable#getWidth",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#getx",
    "class/src/model/Drawable.js~Drawable.html#instance-method-getX",
    "src/model/Drawable.js~Drawable#getX",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#gety",
    "class/src/model/Drawable.js~Drawable.html#instance-method-getY",
    "src/model/Drawable.js~Drawable#getY",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#glyph",
    "class/src/model/Drawable.js~Drawable.html#instance-member-glyph",
    "src/model/Drawable.js~Drawable#glyph",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#height",
    "class/src/model/Drawable.js~Drawable.html#instance-member-height",
    "src/model/Drawable.js~Drawable#height",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#modifiers",
    "class/src/model/Drawable.js~Drawable.html#instance-member-modifiers",
    "src/model/Drawable.js~Drawable#modifiers",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#padding",
    "class/src/model/Drawable.js~Drawable.html#instance-member-padding",
    "src/model/Drawable.js~Drawable#padding",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#setpadding",
    "class/src/model/Drawable.js~Drawable.html#instance-method-setPadding",
    "src/model/Drawable.js~Drawable#setPadding",
    "method"
  ],
  [
    "src/model/drawable.js~drawable#width",
    "class/src/model/Drawable.js~Drawable.html#instance-member-width",
    "src/model/Drawable.js~Drawable#width",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#x",
    "class/src/model/Drawable.js~Drawable.html#instance-member-x",
    "src/model/Drawable.js~Drawable#x",
    "member"
  ],
  [
    "src/model/drawable.js~drawable#y",
    "class/src/model/Drawable.js~Drawable.html#instance-member-y",
    "src/model/Drawable.js~Drawable#y",
    "member"
  ],
  [
    "src/model/score.js",
    "file/src/model/Score.js.html",
    "src/model/Score.js",
    "file"
  ],
  [
    "src/model/score.js~score#constructor",
    "class/src/model/Score.js~Score.html#instance-constructor-constructor",
    "src/model/Score.js~Score#constructor",
    "method"
  ],
  [
    "src/model/score.js~score#createstaff",
    "class/src/model/Score.js~Score.html#instance-method-createStaff",
    "src/model/Score.js~Score#createStaff",
    "method"
  ],
  [
    "src/model/score.js~score#draw",
    "class/src/model/Score.js~Score.html#instance-method-draw",
    "src/model/Score.js~Score#draw",
    "method"
  ],
  [
    "src/model/score.js~score#getstaff",
    "class/src/model/Score.js~Score.html#instance-method-getStaff",
    "src/model/Score.js~Score#getStaff",
    "method"
  ],
  [
    "src/model/score.js~score#render",
    "class/src/model/Score.js~Score.html#instance-method-render",
    "src/model/Score.js~Score#render",
    "method"
  ],
  [
    "src/model/score.js~score#setdata",
    "class/src/model/Score.js~Score.html#instance-method-setData",
    "src/model/Score.js~Score#setData",
    "method"
  ],
  [
    "src/model/staff.js",
    "file/src/model/Staff.js.html",
    "src/model/Staff.js",
    "file"
  ],
  [
    "src/model/staff.js~staff#addnote",
    "class/src/model/Staff.js~Staff.html#instance-method-addNote",
    "src/model/Staff.js~Staff#addNote",
    "method"
  ],
  [
    "src/model/staff.js~staff#addrest",
    "class/src/model/Staff.js~Staff.html#instance-method-addRest",
    "src/model/Staff.js~Staff#addRest",
    "method"
  ],
  [
    "src/model/staff.js~staff#constructor",
    "class/src/model/Staff.js~Staff.html#instance-constructor-constructor",
    "src/model/Staff.js~Staff#constructor",
    "method"
  ],
  [
    "src/model/staff.js~staff#createbar",
    "class/src/model/Staff.js~Staff.html#instance-method-createBar",
    "src/model/Staff.js~Staff#createBar",
    "method"
  ],
  [
    "src/model/staff.js~staff#draw",
    "class/src/model/Staff.js~Staff.html#instance-method-draw",
    "src/model/Staff.js~Staff#draw",
    "method"
  ],
  [
    "src/model/staff.js~staff#getbar",
    "class/src/model/Staff.js~Staff.html#instance-method-getBar",
    "src/model/Staff.js~Staff#getBar",
    "method"
  ],
  [
    "src/model/staff.js~staff#getbars",
    "class/src/model/Staff.js~Staff.html#instance-method-getBars",
    "src/model/Staff.js~Staff#getBars",
    "method"
  ],
  [
    "src/model/staff.js~staff#getclef",
    "class/src/model/Staff.js~Staff.html#instance-method-getClef",
    "src/model/Staff.js~Staff#getClef",
    "method"
  ],
  [
    "src/model/staff.js~staff#getlastbar",
    "class/src/model/Staff.js~Staff.html#instance-method-getLastBar",
    "src/model/Staff.js~Staff#getLastBar",
    "method"
  ],
  [
    "src/model/bar/beat.js",
    "file/src/model/bar/Beat.js.html",
    "src/model/bar/Beat.js",
    "file"
  ],
  [
    "src/model/bar/beat.js~beat#addnote",
    "class/src/model/bar/Beat.js~Beat.html#instance-method-addNote",
    "src/model/bar/Beat.js~Beat#addNote",
    "method"
  ],
  [
    "src/model/bar/beat.js~beat#constructor",
    "class/src/model/bar/Beat.js~Beat.html#instance-constructor-constructor",
    "src/model/bar/Beat.js~Beat#constructor",
    "method"
  ],
  [
    "src/model/bar/beat.js~beat#draw",
    "class/src/model/bar/Beat.js~Beat.html#instance-method-draw",
    "src/model/bar/Beat.js~Beat#draw",
    "method"
  ],
  [
    "src/model/bar/beat.js~beat#format",
    "class/src/model/bar/Beat.js~Beat.html#instance-method-format",
    "src/model/bar/Beat.js~Beat#format",
    "method"
  ],
  [
    "src/model/bar/beat.js~beat#getwidth",
    "class/src/model/bar/Beat.js~Beat.html#instance-method-getWidth",
    "src/model/bar/Beat.js~Beat#getWidth",
    "method"
  ],
  [
    "src/model/bar/note.js",
    "file/src/model/bar/Note.js.html",
    "src/model/bar/Note.js",
    "file"
  ],
  [
    "src/model/bar/note.js~note#constructor",
    "class/src/model/bar/Note.js~Note.html#instance-constructor-constructor",
    "src/model/bar/Note.js~Note#constructor",
    "method"
  ],
  [
    "src/model/bar/note.js~note#draw",
    "class/src/model/bar/Note.js~Note.html#instance-method-draw",
    "src/model/bar/Note.js~Note#draw",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getduration",
    "class/src/model/bar/Note.js~Note.html#instance-method-getDuration",
    "src/model/bar/Note.js~Note#getDuration",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getheads",
    "class/src/model/bar/Note.js~Note.html#instance-method-getHeads",
    "src/model/bar/Note.js~Note#getHeads",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getmaxkey",
    "class/src/model/bar/Note.js~Note.html#instance-method-getMaxKey",
    "src/model/bar/Note.js~Note#getMaxKey",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getminkey",
    "class/src/model/bar/Note.js~Note.html#instance-method-getMinKey",
    "src/model/bar/Note.js~Note#getMinKey",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getorientation",
    "class/src/model/bar/Note.js~Note.html#instance-method-getOrientation",
    "src/model/bar/Note.js~Note#getOrientation",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getsteam",
    "class/src/model/bar/Note.js~Note.html#instance-method-getSteam",
    "src/model/bar/Note.js~Note#getSteam",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getsteamcount",
    "class/src/model/bar/Note.js~Note.html#instance-method-getSteamCount",
    "src/model/bar/Note.js~Note#getSteamCount",
    "method"
  ],
  [
    "src/model/bar/note.js~note#getwidth",
    "class/src/model/bar/Note.js~Note.html#instance-method-getWidth",
    "src/model/bar/Note.js~Note#getWidth",
    "method"
  ],
  [
    "src/model/bar/note.js~note#hasflag",
    "class/src/model/bar/Note.js~Note.html#instance-method-hasFlag",
    "src/model/bar/Note.js~Note#hasFlag",
    "method"
  ],
  [
    "src/model/bar/note.js~note#hassteam",
    "class/src/model/bar/Note.js~Note.html#instance-method-hasSteam",
    "src/model/bar/Note.js~Note#hasSteam",
    "method"
  ],
  [
    "src/model/bar/note.js~note#isrest",
    "class/src/model/bar/Note.js~Note.html#instance-method-isRest",
    "src/model/bar/Note.js~Note#isRest",
    "method"
  ],
  [
    "src/model/bar/note.js~note#setbeam",
    "class/src/model/bar/Note.js~Note.html#instance-method-setBeam",
    "src/model/bar/Note.js~Note#setBeam",
    "method"
  ],
  [
    "src/model/bar/note.js~note#setduration",
    "class/src/model/bar/Note.js~Note.html#instance-method-setDuration",
    "src/model/bar/Note.js~Note#setDuration",
    "method"
  ],
  [
    "src/model/bar/note.js~note#setheads",
    "class/src/model/bar/Note.js~Note.html#instance-method-setHeads",
    "src/model/bar/Note.js~Note#setHeads",
    "method"
  ],
  [
    "src/model/bar/note.js~note#setorientation",
    "class/src/model/bar/Note.js~Note.html#instance-method-setOrientation",
    "src/model/bar/Note.js~Note#setOrientation",
    "method"
  ],
  [
    "src/model/bar/note.js~note#updatewidth",
    "class/src/model/bar/Note.js~Note.html#instance-method-updateWidth",
    "src/model/bar/Note.js~Note#updateWidth",
    "method"
  ],
  [
    "src/model/bar/note.js~note#width",
    "class/src/model/bar/Note.js~Note.html#instance-member-width",
    "src/model/bar/Note.js~Note#width",
    "member"
  ],
  [
    "src/model/bar/noteutil.js",
    "file/src/model/bar/NoteUtil.js.html",
    "src/model/bar/NoteUtil.js",
    "file"
  ],
  [
    "src/model/bar/note/beam.js",
    "file/src/model/bar/note/Beam.js.html",
    "src/model/bar/note/Beam.js",
    "file"
  ],
  [
    "src/model/bar/note/flag.js",
    "file/src/model/bar/note/Flag.js.html",
    "src/model/bar/note/Flag.js",
    "file"
  ],
  [
    "src/model/bar/note/flag.js~flag#constructor",
    "class/src/model/bar/note/Flag.js~Flag.html#instance-constructor-constructor",
    "src/model/bar/note/Flag.js~Flag#constructor",
    "method"
  ],
  [
    "src/model/bar/note/flag.js~flag#draw",
    "class/src/model/bar/note/Flag.js~Flag.html#instance-method-draw",
    "src/model/bar/note/Flag.js~Flag#draw",
    "method"
  ],
  [
    "src/model/bar/note/flag.js~flag#glyph",
    "class/src/model/bar/note/Flag.js~Flag.html#instance-member-glyph",
    "src/model/bar/note/Flag.js~Flag#glyph",
    "member"
  ],
  [
    "src/model/bar/note/head.js",
    "file/src/model/bar/note/Head.js.html",
    "src/model/bar/note/Head.js",
    "file"
  ],
  [
    "src/model/bar/note/head.js~head#compareto",
    "class/src/model/bar/note/Head.js~Head.html#instance-method-compareTo",
    "src/model/bar/note/Head.js~Head#compareTo",
    "method"
  ],
  [
    "src/model/bar/note/head.js~head#constructor",
    "class/src/model/bar/note/Head.js~Head.html#instance-constructor-constructor",
    "src/model/bar/note/Head.js~Head#constructor",
    "method"
  ],
  [
    "src/model/bar/note/head.js~head#draw",
    "class/src/model/bar/note/Head.js~Head.html#instance-method-draw",
    "src/model/bar/note/Head.js~Head#draw",
    "method"
  ],
  [
    "src/model/bar/note/head.js~head#duration",
    "class/src/model/bar/note/Head.js~Head.html#instance-member-duration",
    "src/model/bar/note/Head.js~Head#duration",
    "member"
  ],
  [
    "src/model/bar/note/head.js~head#getkey",
    "class/src/model/bar/note/Head.js~Head.html#instance-method-getKey",
    "src/model/bar/note/Head.js~Head#getKey",
    "method"
  ],
  [
    "src/model/bar/note/head.js~head#glyph",
    "class/src/model/bar/note/Head.js~Head.html#instance-member-glyph",
    "src/model/bar/note/Head.js~Head#glyph",
    "member"
  ],
  [
    "src/model/bar/note/head.js~head#key",
    "class/src/model/bar/note/Head.js~Head.html#instance-member-key",
    "src/model/bar/note/Head.js~Head#key",
    "member"
  ],
  [
    "src/model/bar/note/head.js~head#x",
    "class/src/model/bar/note/Head.js~Head.html#instance-member-x",
    "src/model/bar/note/Head.js~Head#x",
    "member"
  ],
  [
    "src/model/bar/note/head.js~head#y",
    "class/src/model/bar/note/Head.js~Head.html#instance-member-y",
    "src/model/bar/note/Head.js~Head#y",
    "member"
  ],
  [
    "src/model/bar/note/key.js",
    "file/src/model/bar/note/Key.js.html",
    "src/model/bar/note/Key.js",
    "file"
  ],
  [
    "src/model/bar/note/key.js~key#compareto",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-compareTo",
    "src/model/bar/note/Key.js~Key#compareTo",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#constructor",
    "class/src/model/bar/note/Key.js~Key.html#instance-constructor-constructor",
    "src/model/bar/note/Key.js~Key#constructor",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#getkeyname",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-getKeyName",
    "src/model/bar/note/Key.js~Key#getKeyName",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#getoctave",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-getOctave",
    "src/model/bar/note/Key.js~Key#getOctave",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#keyname",
    "class/src/model/bar/note/Key.js~Key.html#instance-member-keyName",
    "src/model/bar/note/Key.js~Key#keyName",
    "member"
  ],
  [
    "src/model/bar/note/key.js~key#name",
    "class/src/model/bar/note/Key.js~Key.html#instance-member-name",
    "src/model/bar/note/Key.js~Key#name",
    "member"
  ],
  [
    "src/model/bar/note/key.js~key#octave",
    "class/src/model/bar/note/Key.js~Key.html#instance-member-octave",
    "src/model/bar/note/Key.js~Key#octave",
    "member"
  ],
  [
    "src/model/bar/note/key.js~key#setkeyname",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-setKeyName",
    "src/model/bar/note/Key.js~Key#setKeyName",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#setoctave",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-setOctave",
    "src/model/bar/note/Key.js~Key#setOctave",
    "method"
  ],
  [
    "src/model/bar/note/key.js~key#tostring",
    "class/src/model/bar/note/Key.js~Key.html#instance-method-toString",
    "src/model/bar/note/Key.js~Key#toString",
    "method"
  ],
  [
    "src/model/bar/note/steam.js",
    "file/src/model/bar/note/Steam.js.html",
    "src/model/bar/note/Steam.js",
    "file"
  ],
  [
    "src/model/bar/note/modifiers/dot.js",
    "file/src/model/bar/note/modifiers/Dot.js.html",
    "src/model/bar/note/modifiers/Dot.js",
    "file"
  ],
  [
    "src/model/clef/trebleclef.js",
    "file/src/model/clef/TrebleClef.js.html",
    "src/model/clef/TrebleClef.js",
    "file"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#constructor",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-constructor-constructor",
    "src/model/clef/TrebleClef.js~TrebleClef#constructor",
    "method"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#draw",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-method-draw",
    "src/model/clef/TrebleClef.js~TrebleClef#draw",
    "method"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#getkeylocation",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-method-getKeyLocation",
    "src/model/clef/TrebleClef.js~TrebleClef#getKeyLocation",
    "method"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#getwidth",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-method-getWidth",
    "src/model/clef/TrebleClef.js~TrebleClef#getWidth",
    "method"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#glyph",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-member-glyph",
    "src/model/clef/TrebleClef.js~TrebleClef#glyph",
    "member"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#middle",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-member-middle",
    "src/model/clef/TrebleClef.js~TrebleClef#middle",
    "member"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#tostring",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-method-toString",
    "src/model/clef/TrebleClef.js~TrebleClef#toString",
    "method"
  ],
  [
    "src/model/clef/trebleclef.js~trebleclef#width",
    "class/src/model/clef/TrebleClef.js~TrebleClef.html#instance-member-width",
    "src/model/clef/TrebleClef.js~TrebleClef#width",
    "member"
  ],
  [
    "src/test/data.js",
    "file/src/test/data.js.html",
    "src/test/data.js",
    "file"
  ],
  [
    "src/ui/viewport.js",
    "file/src/ui/Viewport.js.html",
    "src/ui/Viewport.js",
    "file"
  ],
  [
    "src/util/arraylist.js",
    "file/src/util/ArrayList.js.html",
    "src/util/ArrayList.js",
    "file"
  ],
  [
    "src/util/collections.js",
    "file/src/util/Collections.js.html",
    "src/util/Collections.js",
    "file"
  ],
  [
    "src/util/comparable.js",
    "file/src/util/Comparable.js.html",
    "src/util/Comparable.js",
    "file"
  ],
  [
    "src/util/comparable.js~comparable#compareto",
    "class/src/util/Comparable.js~Comparable.html#instance-method-compareTo",
    "src/util/Comparable.js~Comparable#compareTo",
    "method"
  ],
  [
    "src/util/drawlog.js",
    "file/src/util/DrawLog.js.html",
    "src/util/DrawLog.js",
    "file"
  ],
  [
    "src/util/drawlog.js~drawlog.add",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-add",
    "src/util/DrawLog.js~DrawLog.add",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.addlevel",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-addLevel",
    "src/util/DrawLog.js~DrawLog.addLevel",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.clear",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-clear",
    "src/util/DrawLog.js~DrawLog.clear",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.getinstance",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-getInstance",
    "src/util/DrawLog.js~DrawLog.getInstance",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.print",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-print",
    "src/util/DrawLog.js~DrawLog.print",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.removelevel",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-removeLevel",
    "src/util/DrawLog.js~DrawLog.removeLevel",
    "method"
  ],
  [
    "src/util/drawlog.js~drawlog.setlogenabled",
    "class/src/util/DrawLog.js~DrawLog.html#static-method-setLogEnabled",
    "src/util/DrawLog.js~DrawLog.setLogEnabled",
    "method"
  ],
  [
    "src/util/observable.js",
    "file/src/util/Observable.js.html",
    "src/util/Observable.js",
    "file"
  ],
  [
    "src/util/observable.js~observable#constructor",
    "class/src/util/Observable.js~Observable.html#instance-constructor-constructor",
    "src/util/Observable.js~Observable#constructor",
    "method"
  ],
  [
    "src/util/observable.js~observable#observers",
    "class/src/util/Observable.js~Observable.html#instance-member-observers",
    "src/util/Observable.js~Observable#observers",
    "member"
  ],
  [
    "src/util/util.js",
    "file/src/util/Util.js.html",
    "src/util/Util.js",
    "file"
  ]
]